-- Auto-generated from schema-map-postgres.yaml (map@sha1:8C4F2BC1C4D22EE71E27B5A7968C71E32D8D884D)
-- engine: postgres
-- table:  device_codes

CREATE TABLE IF NOT EXISTS device_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_code_hash BYTEA NOT NULL,
  device_code_hash_key_version VARCHAR(64) NULL,
  device_code BYTEA NOT NULL,
  device_code_key_version VARCHAR(64) NULL,
  user_code_hash BYTEA NOT NULL,
  user_code_hash_key_version VARCHAR(64) NULL,
  client_id VARCHAR(128) NOT NULL,
  scopes JSONB NOT NULL DEFAULT '[]'::jsonb,
  token_payload BYTEA NULL,
  token_payload_key_version VARCHAR(64) NULL,
  interval_sec INTEGER NOT NULL DEFAULT 5,
  approved_at TIMESTAMPTZ(6) NULL,
  expires_at TIMESTAMPTZ(6) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT ux_device_codes_device_code_hash UNIQUE (device_code_hash),
  CONSTRAINT ux_device_codes_user_code_hash UNIQUE (user_code_hash),
  CONSTRAINT chk_device_codes_interval CHECK (interval_sec >= 0)
);
